//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LumoraWebForms {
    public partial class Default : System.Web.UI.Page {

        protected global::System.Web.UI.WebControls.Repeater rptCourses;
    }
}
