//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LumoraWebForms.Pages.Admin {
    public partial class Dashboard : System.Web.UI.Page {

        protected global::System.Web.UI.WebControls.Literal litUsers;
        protected global::System.Web.UI.WebControls.Literal litCourses;
        protected global::System.Web.UI.WebControls.Literal litEnrollments;
        protected global::System.Web.UI.WebControls.Literal litLessons;
        protected global::System.Web.UI.WebControls.Literal litMessages;
        protected global::System.Web.UI.WebControls.Repeater rptRecentCourses;
    }
}
