//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LumoraWebForms.Pages.Admin {
    public partial class Messages : System.Web.UI.Page {

        protected global::System.Web.UI.WebControls.Panel pnlNoMessages;
        protected global::System.Web.UI.WebControls.Repeater rptMessages;
    }
}
