//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LumoraWebForms.Pages {
    public partial class Achievements : System.Web.UI.Page {

        protected global::System.Web.UI.WebControls.Literal litPoints;
        protected global::System.Web.UI.WebControls.Repeater rptBadges;
    }
}
