//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LumoraWebForms.Pages {
    public partial class Courses : System.Web.UI.Page {

        protected global::System.Web.UI.WebControls.Repeater rptCategories;
        protected global::System.Web.UI.WebControls.LinkButton btnAll;
        protected global::System.Web.UI.WebControls.Repeater rptCourses;
        protected global::System.Web.UI.WebControls.Panel pnlNoResults;
    }
}
