//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LumoraWebForms.Pages {
    public partial class CourseDetail : System.Web.UI.Page {

        protected global::System.Web.UI.WebControls.Literal breadcrumbTitle;
        protected global::System.Web.UI.WebControls.Literal courseTitle;
        protected global::System.Web.UI.WebControls.Literal courseCategory;
        protected global::System.Web.UI.WebControls.Literal courseInstructor;
        protected global::System.Web.UI.WebControls.Literal courseEnrollments;
        protected global::System.Web.UI.WebControls.Literal courseDescription;
        protected global::System.Web.UI.WebControls.Panel pnlLessons;
        protected global::System.Web.UI.WebControls.Repeater rptLessons;
        protected global::System.Web.UI.WebControls.Panel pnlEnroll;
        protected global::System.Web.UI.WebControls.Button btnEnroll;
        protected global::System.Web.UI.WebControls.Panel pnlProgress;
        protected global::System.Web.UI.WebControls.Literal progressBar;
        protected global::System.Web.UI.WebControls.Literal progressText;
        protected global::System.Web.UI.WebControls.Literal lessonCount;
        protected global::System.Web.UI.WebControls.Literal enrollmentCount2;
        protected global::System.Web.UI.WebControls.Literal categoryName2;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl coursePrice;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor btnContinue;
    }
}
