//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LumoraWebForms.Pages {
    public partial class Dashboard : System.Web.UI.Page {

        protected global::System.Web.UI.WebControls.Literal litUserName;
        protected global::System.Web.UI.WebControls.Literal litPoints;
        protected global::System.Web.UI.WebControls.Literal litEnrolled;
        protected global::System.Web.UI.WebControls.Literal litCompleted;
        protected global::System.Web.UI.WebControls.Literal litAvgScore;
        protected global::System.Web.UI.WebControls.Literal litTotalPoints;
        protected global::System.Web.UI.WebControls.Panel pnlCourses;
        protected global::System.Web.UI.WebControls.Repeater rptMyCourses;
        protected global::System.Web.UI.WebControls.Panel pnlResults;
        protected global::System.Web.UI.WebControls.Repeater rptResults;
    }
}
