//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LumoraWebForms.Pages {
    public partial class Learn : System.Web.UI.Page {

        protected global::System.Web.UI.WebControls.Literal litCourseTitle;
        protected global::System.Web.UI.WebControls.Repeater rptSidebar;
        protected global::System.Web.UI.WebControls.Literal litOrder;
        protected global::System.Web.UI.WebControls.Literal litTitle;
        protected global::System.Web.UI.WebControls.Literal litDuration;
        protected global::System.Web.UI.WebControls.Literal litContent;
        protected global::System.Web.UI.WebControls.Panel pnlQuizzes;
        protected global::System.Web.UI.WebControls.Repeater rptQuizzes;
        protected global::System.Web.UI.WebControls.TextBox txtDiscussion;
        protected global::System.Web.UI.WebControls.Button btnPost;
        protected global::System.Web.UI.WebControls.Repeater rptDiscussions;
        protected global::System.Web.UI.WebControls.Button btnComplete;
    }
}
